{"uuid": "ff7992b4-caef-4467-bb78-0832fd112087", "children": ["c47da2d8-4f9a-4a5a-bd76-27120559e7db"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。\n", "trace": "  File \"d:\\program files\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\tests\\GponSfu\\conftest.py\", line 17, in login\n    tn = telnet_host(host_ip, username, password)[0]\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\src\\config\\telnet_client.py\", line 30, in telnet_host\n    tn.read_until(b'>>User password: ', timeout=5)\n  File \"d:\\program files\\python37\\lib\\telnetlib.py\", line 315, in read_until\n    self.fill_rawq()\n  File \"d:\\program files\\python37\\lib\\telnetlib.py\", line 524, in fill_rawq\n    buf = self.sock.recv(50)\n"}, "start": 1594345164278, "stop": 1594348066531}], "start": 1594345164278, "stop": 1594348066591}