{"uuid": "faeb9ee1-7432-4f73-beb4-ff91acc39b5f", "children": ["3a7eeeb3-7764-4704-ab29-134d6a6e872d"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。\n", "trace": "  File \"d:\\program files\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\tests\\GponSfu\\conftest.py\", line 17, in login\n    tn = telnet_host(host_ip, username, password)[0]\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\src\\config\\telnet_client.py\", line 36, in telnet_host\n    command_result = tn.read_very_eager().decode('utf-8')\n  File \"d:\\program files\\python37\\lib\\telnetlib.py\", line 364, in read_very_eager\n    self.fill_rawq()\n  File \"d:\\program files\\python37\\lib\\telnetlib.py\", line 524, in fill_rawq\n    buf = self.sock.recv(50)\n"}, "start": 1594187732339, "stop": 1594187834927}], "start": 1594187732339, "stop": 1594187835185}